#!/usr/bin/env python3
"""
app.py — GCS Quote Builder local server.
Run this and a browser opens with the quote builder. All data stays on this machine.

Jobs are stored as JSON in ./jobs/. Generated PDFs/DOCX go in ./jobs/<id>/.
"""
import json
import hashlib
import os
import re
import sys
import threading
import webbrowser
from datetime import datetime, timedelta
from http.server import HTTPServer, BaseHTTPRequestHandler
from socketserver import ThreadingMixIn
from urllib.parse import urlparse, parse_qs

BASE = os.path.dirname(os.path.abspath(__file__))
JOBS_DIR = os.path.join(BASE, "jobs")
LOGO_PATH = os.path.join(BASE, "assets", "logo.png")
CONVEYOR_INTAKE_PATH = os.path.join(BASE, "conveyor_intake.html")

# Load .env if present (optional; firecrawl_extract also reads it directly)
_env_path = os.path.join(BASE, ".env")
if os.path.isfile(_env_path):
    with open(_env_path, encoding="utf-8") as _ef:
        for _line in _ef:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))

# Ports below 1024 require root, so use a high port. The list is tried in
# order; the first one that's free wins (handles "port already in use").
PORT = 8765
PORT_FALLBACKS = [PORT, 8766, 8767, 8780, 8842]

# A job id is generated by new_job_id() as "<YYYYMMDD>_<HHMMSS>__<slug>".
# Anything that doesn't match this exact shape is rejected to prevent a
# crafted id (e.g. containing "..") from escaping the jobs directory.
JOB_ID_RE = re.compile(r'^\d{8}_\d{6}__[A-Za-z0-9_]+$')

os.makedirs(JOBS_DIR, exist_ok=True)


def refresh_conveyor_from_scrape(jdir, data):
    """Always parse cached scrapes with the latest parser on disk."""
    import importlib

    data = data or {}
    if data.get("quote_mode") == "custom_build" or data.get("custom_addons_required"):
        import custom_build_parser
        importlib.reload(custom_build_parser)
        return custom_build_parser.refresh_quote_from_scrape(jdir, data)

    import listing_parser
    importlib.reload(listing_parser)
    return listing_parser.refresh_quote_from_scrape(jdir, data)


def safe_job_dir(jid):
    """Return the absolute path to a job folder, or None if jid is unsafe.

    Validates against the known id pattern AND confirms the resolved path
    stays inside JOBS_DIR, so traversal via symlinks or odd input can't
    read/delete files elsewhere on disk.
    """
    if not jid or not JOB_ID_RE.match(jid):
        return None
    jdir = os.path.realpath(os.path.join(JOBS_DIR, jid))
    root = os.path.realpath(JOBS_DIR)
    if jdir != root and not jdir.startswith(root + os.sep):
        return None
    return jdir

# Lazy imports so a missing lib gives a friendly message, not a crash on boot
def _gen_docx(data, path):
    import docgen
    return docgen.build_quote(data, path)

def _gen_pdf(data, path):
    import pdfgen
    return pdfgen.build_quote_pdf(data, path)


def slugify(s):
    s = re.sub(r'[^a-zA-Z0-9]+', '_', (s or '').strip())
    return re.sub(r'_+', '_', s).strip('_')[:40] or 'quote'


def new_job_id(data):
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    cust = slugify(data.get('cust_company') or data.get('cust_name') or 'quote')
    return f"{stamp}__{cust}"


def new_conveyor_job_id(data):
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    customer = data.get('customer') or {}
    cust = slugify(customer.get('company') or customer.get('contact') or 'conveyor')
    return f"{stamp}__{cust}"


def list_conveyor_jobs():
    out = []
    if not os.path.isdir(JOBS_DIR):
        return out
    for jid in os.listdir(JOBS_DIR):
        jp = os.path.join(JOBS_DIR, jid, "conveyor.json")
        if not os.path.isfile(jp):
            continue
        try:
            with open(jp, encoding='utf-8') as f:
                d = json.load(f)
            li = (d.get('line_items') or [{}])[0]
            out.append({
                "id": jid,
                "cust_company": (d.get('customer') or {}).get('company', ''),
                "quote_num": d.get('quote_num', ''),
                "saved_at": d.get('_saved_at', ''),
                "machine": li.get('model', ''),
                "total": _num((d.get('totals') or {}).get('grand_total')),
            })
        except Exception:
            continue
    out.sort(key=lambda x: x.get('saved_at', ''), reverse=True)
    return out


def default_conveyor_quote():
    today = datetime.now()
    dq = default_quote()
    return {
        "quote_type": "conveyor",
        "quote_mode": "listing_only",
        "custom_addons_required": False,
        "quote_num": today.strftime("GCS-%m%d%Y"),
        "quote_date": today.strftime("%B %d, %Y"),
        "urls": {"listing": "", "request_quote": ""},
        "customer": {
            "company": "",
            "contact": "",
            "email": "",
            "phone": "",
            "street": "",
            "city": "",
            "state": "",
            "zip": "",
            "country": "",
        },
        "rep": {
            "name": "",
            "email": "",
            "phone": "",
        },
        "line_items": [{
            "model": "",
            "addons": "",
            "description": "",
            "amount": "$0.00",
            "lead_time": "",
        }],
        "totals": {
            "subtotal": "",
            "freight": "",
            "tax": "",
            "grand_total": "",
        },
        "equipment_details": [{
            "name": "",
            "description": "",
            "frame": [],
            "idlers": [],
            "undercarriage": [],
            "belt": [],
            "other": [],
            "travel": "",
            "road_portable_option": "",
            "power": "",
            "assembly": "",
            "specifications": [],
            "image_url": "",
        }],
        "field_status": {},
        "scrape_meta": {"listing_scraped_at": "", "quote_scraped_at": "", "errors": []},
    }


def list_jobs():
    out = []
    if not os.path.isdir(JOBS_DIR):
        return out
    for jid in os.listdir(JOBS_DIR):
        jpath = os.path.join(JOBS_DIR, jid, "quote.json")
        if os.path.isfile(jpath):
            try:
                with open(jpath, encoding='utf-8') as f:
                    d = json.load(f)
                eq = sum(_num(i.get('amount')) for i in d.get('equipment_items', []))
                fr = sum(_num(i.get('amount')) for i in d.get('freight_items', []))
                out.append({
                    "id": jid,
                    "cust_company": d.get('cust_company', ''),
                    "cust_name": d.get('cust_name', ''),
                    "date": d.get('date', ''),
                    "rep_name": d.get('rep_name', ''),
                    "total": eq + fr,
                    "saved_at": d.get('_saved_at', ''),
                    "machine": (d.get('equipment_items') or [{}])[0].get('desc', ''),
                })
            except Exception:
                continue
    out.sort(key=lambda x: x.get('saved_at', ''), reverse=True)
    return out


def _num(v):
    try:
        return float(str(v).replace("$", "").replace(",", "").strip() or 0)
    except (ValueError, TypeError):
        return 0.0


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass  # quiet

    # ---- simple shared-password gate ------------------------------------
    # Change the password here (or set APP_PASSWORD env var).
    APP_PASSWORD = os.environ.get("APP_PASSWORD", "crusher2026")
    AUTH_COOKIE = "gcs_auth=" + hashlib.sha256(
        os.environ.get("APP_PASSWORD", "crusher2026").encode()).hexdigest()[:32]

    def _authed(self):
        return self.headers.get("Cookie", "").find(self.AUTH_COOKIE) != -1

    def _login_page(self, msg=""):
        note = f'<p class="err">{msg}</p>' if msg else ""
        body = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>GCS Quote Builder — Sign in</title><style>
body{{font-family:system-ui,sans-serif;background:#11100F;color:#eee;display:flex;
justify-content:center;align-items:center;min-height:100vh;margin:0}}
.card{{background:#1d1c1a;padding:2rem 2.5rem;border-radius:12px;border:1px solid #333;
text-align:center}} h1{{font-size:1.2rem;margin:0 0 1rem;color:#C81010}}
input{{padding:.6rem .8rem;border-radius:8px;border:1px solid #444;background:#11100F;
color:#eee;font-size:1rem;width:220px}} button{{padding:.6rem 1.2rem;margin-left:.5rem;
border-radius:8px;border:0;background:#C81010;color:#fff;font-size:1rem;cursor:pointer}}
.err{{color:#ff6b6b}}</style></head><body><div class="card">
<h1>GCS Quote Builder</h1>{note}
<form method="POST" action="/login">
<input type="password" name="pw" placeholder="Password" autofocus required>
<button>Enter</button></form></div></body></html>"""
        return self._send(200, body, "text/html; charset=utf-8")

    def _require_auth(self):
        """Return True if the request may proceed; otherwise serve login."""
        if self._authed():
            return True
        u = urlparse(self.path)
        if u.path == "/login":
            return True  # handled by do_GET/do_POST below
        if u.path == "/logo":
            return True  # public brand asset; needed by headless PDF rendering
        self.send_response(302)
        self.send_header("Location", "/login")
        self.send_header("Content-Length", "0")
        self.end_headers()
        return False
    # ----------------------------------------------------------------------

    def _send(self, code, body, ctype="application/json"):
        if isinstance(body, (dict, list)):
            body = json.dumps(body).encode('utf-8')
        elif isinstance(body, str):
            body = body.encode('utf-8')
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_file(self, path, ctype, download_name=None):
        if not os.path.isfile(path):
            return self._send(404, {"error": "not found"})
        with open(path, 'rb') as f:
            body = f.read()
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        if download_name:
            self.send_header("Content-Disposition", f'attachment; filename="{download_name}"')
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        u = urlparse(self.path)
        q = parse_qs(u.query)
        if u.path == "/login":
            return self._login_page()
        if not self._require_auth():
            return
        if u.path == "/" or u.path == "/index.html" or u.path == "/conveyor":
            return self._send(200, CONVEYOR_INTAKE_HTML, "text/html; charset=utf-8")
        if u.path == "/conveyor/quote":
            return self._conveyor_quote(q.get('id', [''])[0])
        if u.path == "/conveyor/download":
            self._conveyor_download(q.get('id', [''])[0])
            return
        if u.path == "/api/conveyor/defaults":
            return self._send(200, default_conveyor_quote())
        if u.path == "/api/conveyor/config":
            import firecrawl_extract
            return self._send(200, {"has_api_key": bool(firecrawl_extract.get_api_key())})
        if u.path == "/api/conveyor/jobs":
            return self._send(200, list_conveyor_jobs())
        if u.path == "/api/conveyor/job":
            jdir = safe_job_dir(q.get('id', [''])[0])
            if jdir is None:
                return self._send(400, {"error": "bad id"})
            jp = os.path.join(jdir, "conveyor.json")
            if os.path.isfile(jp):
                with open(jp, encoding='utf-8') as f:
                    data = json.load(f)
                data = refresh_conveyor_from_scrape(jdir, data)
                return self._send(200, data)
            return self._send(404, {"error": "not found"})
        if u.path == "/api/jobs":
            return self._send(200, list_jobs())
        if u.path == "/api/job":
            jdir = safe_job_dir(q.get('id', [''])[0])
            if jdir is None:
                return self._send(400, {"error": "bad id"})
            jp = os.path.join(jdir, "quote.json")
            if os.path.isfile(jp):
                with open(jp, encoding='utf-8') as f:
                    return self._send(200, json.load(f))
            return self._send(404, {"error": "not found"})
        if u.path == "/api/defaults":
            return self._send(200, default_quote())
        if u.path == "/download":
            jid = q.get('id', [''])[0]
            fmt = q.get('fmt', ['pdf'])[0]
            self._download(jid, fmt)
            return
        if u.path == "/logo":
            if os.path.isfile(LOGO_PATH):
                return self._send_file(LOGO_PATH, "image/png")
            return self._send(404, b"")
        return self._send(404, {"error": "not found"})

    def do_POST(self):
        u = urlparse(self.path)
        length = int(self.headers.get('Content-Length', 0))
        raw = self.rfile.read(length) if length else b'{}'

        if u.path == "/login":
            pw = raw.decode('utf-8', 'replace')
            # accept form-encoded or JSON
            if "=" in pw and not pw.strip().startswith("{"):
                from urllib.parse import parse_qsl
                pw = dict(parse_qsl(pw)).get("pw", "")
            else:
                try:
                    pw = json.loads(pw).get("pw", "")
                except Exception:
                    pw = ""
            if pw == self.APP_PASSWORD:
                self.send_response(303)
                self.send_header("Location", "/")
                self.send_header("Set-Cookie", self.AUTH_COOKIE + "; Path=/; HttpOnly; Max-Age=2592000")
                self.send_header("Content-Length", "0")
                self.end_headers()
            else:
                self._login_page("Wrong password — try again")
            return

        if not self._require_auth():
            return
        try:
            data = json.loads(raw.decode('utf-8'))
        except Exception:
            return self._send(400, {"error": "bad json"})

        if u.path == "/api/save":
            return self._save(data)
        if u.path == "/api/conveyor/save":
            return self._save_conveyor(data)
        if u.path == "/api/conveyor/extract":
            return self._conveyor_extract(data)
        if u.path == "/api/conveyor/render":
            return self._conveyor_render(data)
        if u.path == "/conveyor/screenshot":
            return self._conveyor_screenshot(data)
        if u.path == "/api/delete":
            jdir = safe_job_dir(data.get('id', ''))
            if jdir is None:
                return self._send(400, {"error": "bad id"})
            if os.path.isdir(jdir):
                import shutil
                shutil.rmtree(jdir)
                return self._send(200, {"ok": True})
            return self._send(404, {"error": "not found"})
        return self._send(404, {"error": "not found"})

    def _save(self, data):
        # Reuse the existing id only if it passes validation; otherwise mint a
        # fresh one. This stops a crafted _id from steering writes out of jobs/.
        jid = data.get('_id')
        if not jid or safe_job_dir(jid) is None:
            jid = new_job_id(data)
        data['_id'] = jid
        data['_saved_at'] = datetime.now().isoformat(timespec='seconds')
        jdir = os.path.join(JOBS_DIR, jid)
        os.makedirs(jdir, exist_ok=True)
        with open(os.path.join(jdir, "quote.json"), 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        return self._send(200, {"ok": True, "id": jid})

    def _download(self, jid, fmt):
        jdir = safe_job_dir(jid)
        if jdir is None:
            return self._send(400, {"error": "bad id"})
        jp = os.path.join(jdir, "quote.json")
        if not os.path.isfile(jp):
            return self._send(404, {"error": "save the quote first"})
        with open(jp, encoding='utf-8') as f:
            data = json.load(f)
        if os.path.isfile(LOGO_PATH):
            data['_logo_path'] = LOGO_PATH
        base = slugify(data.get('cust_company') or data.get('cust_name') or 'quote')
        name = f"GCS_Quote_{base}"
        try:
            if fmt == "docx":
                out = os.path.join(jdir, name + ".docx")
                _gen_docx(data, out)
                return self._send_file(out,
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    name + ".docx")
            else:
                out = os.path.join(jdir, name + ".pdf")
                _gen_pdf(data, out)
                return self._send_file(out, "application/pdf", name + ".pdf")
        except Exception as e:
            return self._send(500, {"error": str(e)})

    def _save_conveyor(self, data):
        jid = data.get('_id')
        if not jid or safe_job_dir(jid) is None:
            jid = new_conveyor_job_id(data)
        data['_id'] = jid
        data['_saved_at'] = datetime.now().isoformat(timespec='seconds')
        data['quote_type'] = 'conveyor'
        jdir = os.path.join(JOBS_DIR, jid)
        os.makedirs(jdir, exist_ok=True)
        with open(os.path.join(jdir, "conveyor.json"), 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        return self._send(200, {"ok": True, "id": jid})

    def _conveyor_extract(self, data):
        import firecrawl_extract
        urls = data.get('urls') or {}
        listing = (urls.get('listing') or '').strip()
        if not listing:
            return self._send(400, {"error": "listing URL is required"})
        request_quote = (urls.get('request_quote') or '').strip()
        custom_addons = bool(data.get('custom_addons_required'))
        quote_mode = data.get('quote_mode') or ('custom_build' if custom_addons else 'listing_only')
        pasted_addons = ""
        req_items = data.get('line_items') or []
        if req_items:
            pasted_addons = (req_items[0] or {}).get('addons') or ''
        if not custom_addons:
            request_quote = ""
        jid = data.get('job_id')
        jdir = safe_job_dir(jid) if jid else None
        if not jdir:
            jid = new_conveyor_job_id({"customer": data.get('customer') or {}})
            jdir = os.path.join(JOBS_DIR, jid)
            os.makedirs(jdir, exist_ok=True)
        try:
            result = firecrawl_extract.run_extraction(
                listing,
                request_quote or None,
                job_dir=jdir,
                force=bool(data.get('force')),
                custom_addons_required=custom_addons,
                quote_mode=quote_mode,
            )
            # Merge into existing conveyor.json if present
            jp = os.path.join(jdir, "conveyor.json")
            base = default_conveyor_quote()
            if os.path.isfile(jp):
                with open(jp, encoding='utf-8') as f:
                    base = json.load(f)
            base['urls'] = {"listing": listing, "request_quote": request_quote}
            base['quote_mode'] = result.get('quote_mode', quote_mode)
            base['custom_addons_required'] = result.get('custom_addons_required', custom_addons)
            base['_id'] = jid
            if custom_addons:
                import custom_build_parser
                existing_items = list(base.get('line_items') or [])
                existing_totals = dict(base.get('totals') or {})
                new_items = list(result.get('line_items') or [])
                if existing_items and new_items:
                    saved = existing_items[0] or {}
                    keep = {}
                    if str(saved.get('lead_time') or '').strip():
                        keep['lead_time'] = saved['lead_time']
                    if custom_build_parser._meaningful_custom_price(saved.get('amount')):
                        keep['amount'] = saved['amount']
                    new_items[0] = {**new_items[0], **keep}
                base['line_items'] = new_items or existing_items
                base['equipment_details'] = result.get('equipment_details') or base.get('equipment_details')
                merged_totals = dict(result.get('totals') or {})
                for key in ('subtotal', 'freight', 'tax', 'grand_total'):
                    val = existing_totals.get(key)
                    if key == 'subtotal':
                        if custom_build_parser._meaningful_custom_price(val):
                            merged_totals[key] = val
                    elif str(val or '').strip():
                        merged_totals[key] = val
                base['totals'] = merged_totals
            else:
                base['line_items'] = result.get('line_items') or base.get('line_items')
                base['equipment_details'] = result.get('equipment_details') or base.get('equipment_details')
                base['totals'] = result.get('totals') or base.get('totals')
            base['field_status'] = result.get('field_status') or {}
            if custom_addons and base.get('line_items'):
                base['line_items'][0]['addons'] = pasted_addons
                fs = dict(base.get('field_status') or {})
                fs['custom_addons'] = 'ok' if pasted_addons.strip() else 'missing'
                base['field_status'] = fs
            base['scrape_meta'] = result.get('scrape_meta') or {}
            base = refresh_conveyor_from_scrape(jdir, base)
            with open(jp, 'w', encoding='utf-8') as f:
                json.dump(base, f, indent=2)
            out = dict(base)
            out['field_status'] = base.get('field_status')
            return self._send(200, out)
        except Exception as e:
            return self._send(500, {"error": str(e)})

    def _conveyor_render(self, data):
        import conveyor_render
        jid = data.get('_id') or data.get('id')
        jdir = safe_job_dir(jid)
        if jdir is None:
            return self._send(400, {"error": "bad id"})
        jp = os.path.join(jdir, "conveyor.json")
        if not os.path.isfile(jp):
            return self._send(404, {"error": "save the quote first"})
        with open(jp, encoding='utf-8') as f:
            quote_data = json.load(f)
        # Allow inline updates from client before render
        for key in ('customer', 'rep', 'line_items', 'totals', 'equipment_details',
                    'quote_num', 'quote_date', 'urls', 'quote_mode', 'custom_addons_required'):
            if key in data:
                quote_data[key] = data[key]
        out_path = os.path.join(jdir, "GCS_Conveyor_Quote.html")
        try:
            conveyor_render.write_quote_html(quote_data, out_path)
            with open(jp, 'w', encoding='utf-8') as f:
                json.dump(quote_data, f, indent=2)
            return self._send(200, {"ok": True, "id": jid, "html_path": out_path})
        except Exception as e:
            return self._send(500, {"error": str(e)})

    def _conveyor_quote(self, jid):
        jdir = safe_job_dir(jid)
        if jdir is None:
            return self._send(400, {"error": "bad id"})
        html_path = os.path.join(jdir, "GCS_Conveyor_Quote.html")
        if os.path.isfile(html_path):
            with open(html_path, encoding='utf-8') as f:
                return self._send(200, f.read(), "text/html; charset=utf-8")
        jp = os.path.join(jdir, "conveyor.json")
        if not os.path.isfile(jp):
            return self._send(404, {"error": "not found"})
        import conveyor_render
        with open(jp, encoding='utf-8') as f:
            data = json.load(f)
        html_out = conveyor_render.render_quote_html(data)
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_out)
        return self._send(200, html_out, "text/html; charset=utf-8")

    def _conveyor_download(self, jid):
        jdir = safe_job_dir(jid)
        if jdir is None:
            return self._send(400, {"error": "bad id"})
        html_path = os.path.join(jdir, "GCS_Conveyor_Quote.html")
        if not os.path.isfile(html_path):
            jp = os.path.join(jdir, "conveyor.json")
            if not os.path.isfile(jp):
                return self._send(404, {"error": "build the quote first"})
            import conveyor_render
            with open(jp, encoding='utf-8') as f:
                data = json.load(f)
            html_out = conveyor_render.render_quote_html(data)
            with open(html_path, 'w', encoding='utf-8') as f:
                f.write(html_out)
        with open(os.path.join(jdir, "conveyor.json"), encoding='utf-8') as f:
            data = json.load(f)
        customer = data.get('customer') or {}
        base = slugify(customer.get('company') or customer.get('contact') or 'conveyor')
        name = f"GCS_Conveyor_Quote_{base}.pdf"
        pdf_path = os.path.join(jdir, name)
        try:
            import conveyor_pdf
            conveyor_pdf.build_conveyor_pdf(pdf_path, html_path=html_path, data=data)
            return self._send_file(pdf_path, "application/pdf", name)
        except Exception as e:
            return self._send(500, {"error": str(e)})

    def _conveyor_screenshot(self, data):
        """POST {html, id?} → Playwright page screenshots assembled into a letter PDF."""
        html = (data or {}).get("html") or ""
        if not str(html).strip():
            return self._send(400, {"error": "missing html"})

        jid = (data or {}).get("id") or ""
        jdir = safe_job_dir(jid) if jid else None
        if jdir is None:
            jdir = os.path.join(JOBS_DIR, "_screenshots")
            os.makedirs(jdir, exist_ok=True)
            base = "conveyor"
        else:
            jp = os.path.join(jdir, "conveyor.json")
            base = "conveyor"
            if os.path.isfile(jp):
                try:
                    with open(jp, encoding="utf-8") as f:
                        quote = json.load(f)
                    customer = quote.get("customer") or {}
                    base = slugify(customer.get("company") or customer.get("contact") or "conveyor")
                except Exception:
                    pass

        host = self.headers.get("Host") or f"127.0.0.1:{PORT}"
        base_url = f"http://{host}"
        name = f"GCS_Conveyor_Quote_{base}_screenshot.pdf"
        pdf_path = os.path.join(jdir, name)
        try:
            import conveyor_screenshot
            conveyor_screenshot.build_screenshot_pdf(
                pdf_path, html=html, base_url=base_url
            )
            return self._send_file(pdf_path, "application/pdf", name)
        except Exception as e:
            return self._send(500, {"error": str(e)})


def default_quote():
    today = datetime.now()
    valid = today + timedelta(days=30)
    return {
        "company_name": "GrinderCrusherScreen",
        "company_address": "1772 Corn Rd, Smyrna, GA 30080",
        "company_phone": "770-433-2670",
        "subtitle": "Equipment & Freight Estimate",
        "date": today.strftime("%B %d, %Y"),
        "valid_until": valid.strftime("%B %d, %Y"),
        "rep_name": "Kohl Schaffer",
        "rep_title": "Southeast Regional Sales Representative",
        "rep_mobile": "678-689-5571",
        "cust_name": "",
        "cust_company": "",
        "cust_city": "",
        "cust_email": "",
        "equipment_items": [{"desc": "Machine / Equipment", "amount": ""}],
        "freight_items": [{"desc": "Freight to Customer", "amount": ""}],
        "payment_terms": "Wire transfer - Financing options available",
        "lead_time": "",
        "freight_note": "Freight estimate is approximate. Final charges confirmed at time of shipment.",
        "additional_notes": "",
        "footer": "Thank you for the opportunity to earn your business.  •  GrinderCrusherScreen.com  •  770-433-2670",
    }


class ThreadingHTTPServer(ThreadingMixIn, HTTPServer):
    daemon_threads = True


def _bind():
    """Bind to the first free port from PORT_FALLBACKS. Returns (server, port)."""
    last_err = None
    for p in PORT_FALLBACKS:
        try:
            return ThreadingHTTPServer(("127.0.0.1", p), Handler), p
        except OSError as e:
            last_err = e
            continue
    raise SystemExit(
        "Could not start: all candidate ports are busy. "
        f"Close other copies of the app and try again. ({last_err})")


def main():
    # load the UI from disk so it's easy to tweak
    global CONVEYOR_INTAKE_HTML
    with open(CONVEYOR_INTAKE_PATH, encoding='utf-8') as f:
        CONVEYOR_INTAKE_HTML = f.read()

    # Bind first so a failed start never opens a dead browser tab.
    server, port = _bind()
    url = f"http://127.0.0.1:{port}/"
    conveyor_url = f"http://127.0.0.1:{port}/conveyor"
    print("=" * 60)
    print("  GCS Quote Builder is running")
    print("  Conveyor quotes:   http://127.0.0.1:%d/  (also /conveyor)" % port)
    print("  (This window must stay open while you use the app.)")
    print("  Close this window to stop the app.")
    print("=" * 60)
    threading.Timer(1.0, lambda: webbrowser.open(conveyor_url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


INDEX_HTML = ""  # filled in main()
CONVEYOR_INTAKE_HTML = ""  # filled in main()

if __name__ == "__main__":
    main()
